services:
  - type: web
    name: exhibition-app
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node build/index.js
    envVars:
      - key: TURSO_DB_URL
        sync: false
      - key: TURSO_DB_AUTH_TOKEN
        sync: false
      - key: NODE_VERSION
        value: 18.0.0
